title: Bowen Zhang # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Modeling Analytics at JPMorgan Chase & Co. with 5 years working experiences in consumer banking, including fraud strategies, mortgage and credit card loss forecasting
  <br><br>
  Full-stack engineer working in progress 
  <br><br>
  <a href="www.linkedin.com/in/bowen-zhang-83029a56">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
